Updated build yml

diff --git a/.github/workflows/build-dotnet.yml b/.github/workflows/build-dotnet.yml
--- a/.github/workflows/build-dotnet.yml
+++ b/.github/workflows/build-dotnet.yml
@@ -51,6 +51,18 @@ jobs:
           path: |
             **/TestResults/*.xml
             **/TestResults/*.trx
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Dotnet Tests
+          path: '**/TestResults/TestOutputResults.xml'
+          reporter: dotnet-trx
+
+      - name: Read output variables
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
       - name: Deploy GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
